name: devops task

on:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests/commit-tests

  build:
    needs: [unit-tests]
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
  integration-tests:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run integration tests
      run: |
        python -m unittest discover tests/release-tests
  
  deploy:
    needs: [integration-tests]
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        python3 main.py
    - name: Add to crontab
      run: |
        (crontab -l | grep -v 'python3 $(pwd)/main.py') | crontab -
        (crontab -l ; echo "* * * * * python3 $(pwd)/main.py") | crontab -
